### ISSUE TITLE
response 9001

### ISSUE THREAD

**Issue by ANASS812** [kormax/google-smart-tap#1]
Hello @kormax ,

I wanted to express my appreciation for your excellent work on Smart Tap; it's truly fascinating. Thank you for sharing your insights. I do have a question—I've created a pass using the Google Wallet API, and I believe I've configured both the pass and the reader correctly (at least I hope so). However, when I request the APDU getdata, I receive the 9001 response, indicating "No passes" according to your notes (even though my pass is consistently in front of the reader). Could you provide more information or resources to help me address this issue? 
Thanks in advance.

**Comment by kormax** [comment]
I can't really be sure about what's happening without having a look at implementation, but here are two(4) of my guesses:

- You could be trying to request an invalid collector ID due to wrong hex/digit conversion. Collector ID might look like a hexadecimal value, but it's actually a decimal, and should be converted accordingly.
- You could be requesting wrong service type which doesn't match your pass type. For best compatibility, service list record should contain ALL or ALL_EXCEPT_PPSE.
- You could be attempting a wrong command flow or request data after failed secure channel creation.

**Comment by ANASS812** [comment]
Thank you for your reply:

- The secure channel was successfully established, and my Collector ID was in decimal format.
- I think this might be the issue. Could you guide me to appropriate resources or provide more information on this matter?
- As mentioned earlier, the secure channel was successfully created.

**Comment by kormax** [comment]
Look at the command and data examples for GET DATA down in README.

slr -> str record value should match (0x00)

**Comment by ANASS812** [comment]
Thanks @kormax ! I will look into this solution."
